<?php
$this->headScript()
     ->appendScript('$(function(){
         $( "#num_empl" ).focus();
     });');
?>
<div id="wrap-login-form">
    <div class="logo"><a href="/"><img src="/images/logo-login.png" /></a></div>
    <div class="form-login"><?php echo $this->form; ?></div>
    <div class="alert"><?php echo $this->message; ?></div>
    <div class="title">Acceder a<br /><span>775Desk</span></div>
</div>