<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-US">
<head>
<?php
	echo $this->headTitle();
	echo $this->headMeta();
	echo $this->headLink( array( 'rel' => 'favicon',
								 'href' => '/favicon.ico' ),
						  'PREPEND' )
			  ->appendStylesheet('/style.css')
			  ->appendStylesheet('/style-ie.css', 'screen', 'IE')
			  ->appendStylesheet('/css-jquery/jquery.ui.all.css');
	echo $this->headScript()
			  ->prependFile('/js/script.js')
			  ->prependFile('/js/ajax.js')
			  ->prependFile('/js/jquery/jquery.ui.widget.min.js')
			  ->prependFile('/js/jquery/jquery.ui.effect.min.js')
			  ->prependFile('/js/jquery/jquery.ui.core.min.js')
			  ->prependFile('/js/jquery/jquery-1.8.2.js');
?>
</head>
<body>
<div id="wrap">
	<div id="header">
		<div id="menu">
			<?php $mainNav = $this->navigation()->findOneByLabel('main nav'); ?>
			<?php echo $this->navigation()->menu()->renderMenu($mainNav); ?>
			<div class="name-user"><?php echo Zend_Auth::getInstance()->getStorage()->read()->name; ?></div>
			<div class="clear"></div>
		</div>
	</div>
	<div id="content">
		<div id="logo"><a href="/"><img src="/images/logo.png" title="Claro" /></a></div>
		<div id="mainContent">
			<?php if( empty($this->message) ===  false ): ?>
				<div class="message"><?php echo nl2br(trim($this->message)); ?></div>
			<?php endif; ?>
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
</div>

<div id="copyright">
	<div>&copy; <?php echo date('Y'); ?> (Alpha)</div>
</div>

</body>
</html>