<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-US">
<head>
<?php
    echo $this->headTitle();
    echo $this->headMeta();
    echo $this->headLink(
                   array(
                       'rel' => 'favicon',
                       'href' => '/favicon.ico'
                   ),
                   'PREPEND'
              )
              ->appendStylesheet('/style-ie.css', 'screen', 'IE')
              ->appendStylesheet('/style.css');
    echo $this->headScript()
              ->prependFile('/js/jquery/jquery-1.8.2.js');
?>
</head>
<body class="body-login">
<div id="wrap-login">
    <div id="content-login"><?php echo $this->layout()->content; ?></div>
</div>

<div id="copyright">
    <div>&copy; <?php echo date('Y'); ?> (Alpha)</div>
</div>

</body>
</html>